/**
 * 국가명(영문/한국어) 매핑 및 flagcdn 국기 이미지 URL 생성 유틸리티
 */
const nationCodeMap = {
  // 영문 국가명
  'England': 'gb-eng',
  'Wales': 'gb-wls',
  'Scotland': 'gb-sct',
  'Northern Ireland': 'gb-nir',
  'Ghana': 'gh',
  'Gambia': 'gm',
  'Greece': 'gr',
  'Guinea': 'gn',
  'Guinea-Bissau': 'gw',
  'Nigeria': 'ng',
  'Netherlands': 'nl',
  'Norway': 'no',
  'New Zealand': 'nz',
  'South Korea': 'kr',
  'Denmark': 'dk',
  'Germany': 'de',
  'Luxembourg': 'lu',
  'Mali': 'ml',
  'Morocco': 'ma',
  'Mozambique': 'mz',
  'USA': 'us',
  'United States': 'us',
  'Belgium': 'be',
  'Bosnia and Herzegovina': 'ba',
  'Bosnia-Herzegovina': 'ba',
  'Burkina Faso': 'bf',
  'Bulgaria': 'bg',
  'Brazil': 'br',
  'Senegal': 'sn',
  'Serbia': 'rs',
  'Sweden': 'se',
  'Switzerland': 'ch',
  'Spain': 'es',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'Argentina': 'ar',
  'Iceland': 'is',
  'Haiti': 'ht',
  'Ireland': 'ie',
  'Albania': 'al',
  'Algeria': 'dz',
  'Ecuador': 'ec',
  'Austria': 'at',
  'Uruguay': 'uy',
  'Uzbekistan': 'uz',
  'Ukraine': 'ua',
  'Israel': 'il',
  'Egypt': 'eg',
  'Italy': 'it',
  'Japan': 'jp',
  'Jamaica': 'jm',
  'Georgia': 'ge',
  'Czech Republic': 'cz',
  'Chile': 'cl',
  'Cameroon': 'cm',
  'Canada': 'ca',
  'Ivory Coast': 'ci',
  "Cote d'Ivoire": 'ci',
  'Colombia': 'co',
  'Congo DR': 'cd',
  'DR Congo': 'cd',
  'Croatia': 'hr',
  'Turkey': 'tr',
  'Paraguay': 'py',
  'Portugal': 'pt',
  'Poland': 'pl',
  'France': 'fr',
  'Hungary': 'hu',
  'Australia': 'au',

  // 한국어 국가명 매핑 (fallback)
  '잉글랜드': 'gb-eng',
  '웨일스': 'gb-wls',
  '스코틀랜드': 'gb-sct',
  '북아일랜드': 'gb-nir',
  '독일': 'de',
  '스페인': 'es',
  '프랑스': 'fr',
  '이탈리아': 'it',
  '네덜란드': 'nl',
  '브라질': 'br',
  '아르헨티나': 'ar',
  '포르투갈': 'pt',
  '벨기에': 'be',
  '노르웨이': 'no',
  '스웨덴': 'se',
  '덴마크': 'dk',
  '대한민국': 'kr',
  '일본': 'jp',
  '미국': 'us',
  '캐나다': 'ca',
  '우루과이': 'uy',
  '콜롬비아': 'co',
  '스위스': 'ch',
  '오스트리아': 'at',
  '크로아티아': 'hr',
  '세르비아': 'rs',
  '우크라이나': 'ua',
  '그리스': 'gr',
  '터키': 'tr',
  '튀르키예': 'tr',
  '모로코': 'ma',
  '세네갈': 'sn',
  '나이지리아': 'ng',
  '이집트': 'eg',
  '가나': 'gh',
  '코트디부아르': 'ci',
  '카메룬': 'cm',
  '알제리': 'dz',
  '아일랜드': 'ie',
  '체코': 'cz',
  '폴란드': 'pl',
  '헝가리': 'hu',
  '루마니아': 'ro',
  '슬로바키아': 'sk',
  '슬로베니아': 'si',
  '아이슬란드': 'is',
  '호주': 'au',
  '뉴질랜드': 'nz',
  '에콰도르': 'ec',
  '파라과이': 'py',
  '칠레': 'cl',
  '자메이카': 'jm',
  '말리': 'ml',
  '부르키나파소': 'bf',
  '기니': 'gn',
  '감비아': 'gm',
  '모잠비크': 'mz',
  '콩고': 'cd',
  '조지아': 'ge',
  '우즈베키스탄': 'uz',
  '이스라엘': 'il',
  '룩셈부르크': 'lu',
  '알바니아': 'al',
  '불가리아': 'bg',
  '보스니아': 'ba',
  '아이티': 'ht'
};

export const getCountryCode = (nationality, koreanNation) => {
  if (nationality && nationCodeMap[nationality]) {
    return nationCodeMap[nationality];
  }
  if (koreanNation && nationCodeMap[koreanNation]) {
    return nationCodeMap[koreanNation];
  }
  return null;
};

export const getFlagUrl = (nationality, koreanNation, width = 40) => {
  const code = getCountryCode(nationality, koreanNation);
  if (!code) return null;
  return `https://flagcdn.com/w${width}/${code}.png`;
};

export default { getCountryCode, getFlagUrl };

