-- TEAM_STATS 및 PLAYER_STATS 테이블에 CLEAN_SHEETS(무실점 경기 횟수) 컬럼을 안전하게 추가하는 마이그레이션 스크립트
DECLARE
    column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TEAM_STATS' AND COLUMN_NAME = 'CLEAN_SHEETS';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TEAM_STATS ADD (CLEAN_SHEETS NUMBER DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO column_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'PLAYER_STATS' AND COLUMN_NAME = 'CLEAN_SHEETS';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PLAYER_STATS ADD (CLEAN_SHEETS NUMBER DEFAULT 0 NOT NULL)';
    END IF;
END;
/
