-- =========================================================================
-- 마이그레이션: Oracle Autonomous Database(OCI ADB) 타임존 KST(+09:00) 보정
-- 설명: OCI 클라우드 호스트 OS가 UTC로 동작함에 따라, SYSTIMESTAMP/SYSDATE를 
--       사용할 경우 세션 타임존과 무관하게 UTC(9시간 이전 시각)가 저장되는 현상을 방지.
--       세션 타임존(Asia/Seoul)을 따르는 LOCALTIMESTAMP 및 CURRENT_DATE로 기본값 전환.
-- =========================================================================

-- 1. 회원 및 통계
ALTER TABLE USERS MODIFY (CREATED_AT DEFAULT LOCALTIMESTAMP);
ALTER TABLE USER_PREDICTS MODIFY (UPDATED_AT DEFAULT LOCALTIMESTAMP);

-- 2. 커뮤니티 게시글, 댓글, 추천, 첨부파일
ALTER TABLE POSTS MODIFY (CREATED_AT DEFAULT LOCALTIMESTAMP);
ALTER TABLE COMMENTS MODIFY (CREATED_AT DEFAULT LOCALTIMESTAMP);
ALTER TABLE POST_LIKES MODIFY (CREATED_AT DEFAULT LOCALTIMESTAMP);
ALTER TABLE COMMENT_LIKES MODIFY (CREATED_AT DEFAULT LOCALTIMESTAMP);
ALTER TABLE POST_ATTACHMENTS MODIFY (CREATED_AT DEFAULT LOCALTIMESTAMP);

-- 3. 승부예측 및 포인트 변동
ALTER TABLE PREDICTIONS MODIFY (CREATED_AT DEFAULT LOCALTIMESTAMP);
ALTER TABLE POINT_HISTORY MODIFY (CREATED_AT DEFAULT LOCALTIMESTAMP);

-- 4. 포인트샵, 인벤토리, 주문, 거래 원장
ALTER TABLE USER_INVENTORY MODIFY (PURCHASED_AT DEFAULT CURRENT_DATE);
ALTER TABLE ITEM_ORDERS MODIFY (ORDERED_AT DEFAULT CURRENT_DATE);
ALTER TABLE POINT_TRANSACTIONS MODIFY (CREATED_AT DEFAULT CURRENT_DATE);
ALTER TABLE SHOP_ITEMS MODIFY (CREATED_AT DEFAULT CURRENT_DATE);

-- 5. 커스텀 스쿼드 및 AI 경기
ALTER TABLE CUSTOM_TEAMS MODIFY (CREATED_AT DEFAULT LOCALTIMESTAMP);
ALTER TABLE AI_MATCHES MODIFY (CREATED_AT DEFAULT LOCALTIMESTAMP);

-- 6. 구단 정보 및 통계
ALTER TABLE TEAMS MODIFY (UPDATED_AT DEFAULT LOCALTIMESTAMP);
ALTER TABLE TEAM_STATS MODIFY (UPDATED_AT DEFAULT LOCALTIMESTAMP);
